sonar.projectKey=edu526_devo-cli
sonar.organization=edu526

sonar.sources=cli_tool
sonar.tests=tests
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,**/__pycache__/**,cli_tool/_version.py

sonar.exclusions=\
  venv/**,\
  build/**,\
  dist/**,\
  **/__pycache__/**,\
  cli_tool/_version.py
